import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.CCM_HOME = fs.mkdtempSync(path.join(os.tmpdir(), 'ccm-sess-'));
process.env.CCM_CLAUDE_DIR = path.join(process.env.CCM_HOME, 'fake-claude');
const { slugForPath, listTranscripts, allSessions, listSessions, sessionMeta, isUserFacing, isSyntheticPrompt, promptTitle } = await import('../src/sessions.js');
const { profileDir } = await import('../src/paths.js');
const { registerProfile } = await import('../src/registry.js');

test('slugForPath matches Claude Code project-folder naming', () => {
  assert.equal(slugForPath('C:\\Users\\Thinkpad'), 'C--Users-Thinkpad');
  assert.equal(slugForPath('C:\\Users\\Thinkpad\\projects\\ccm'), 'C--Users-Thinkpad-projects-ccm');
  assert.equal(slugForPath('C:\\a b\\c.d'), 'C--a-b-c-d');
});

test('listTranscripts finds jsonl sessions with ids and mtimes', () => {
  registerProfile('t1');
  const dir = path.join(profileDir('t1'), 'projects', 'C--x');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'aaaa-bbbb.jsonl'), '{}');
  fs.writeFileSync(path.join(dir, 'not-a-session.txt'), '');
  const list = listTranscripts(profileDir('t1'), 'C--x');
  assert.equal(list.length, 1);
  assert.equal(list[0].id, 'aaaa-bbbb');
  assert.ok(list[0].mtime > 0);
  assert.deepEqual(listTranscripts(profileDir('t1'), 'C--missing'), []);
});

test('allSessions(null) sweeps every project folder and tags slugs', () => {
  const dir2 = path.join(profileDir('t1'), 'projects', 'C--y');
  fs.mkdirSync(dir2, { recursive: true });
  fs.writeFileSync(path.join(dir2, 'cccc-dddd.jsonl'), '{}');
  const here = allSessions('C--x');
  assert.deepEqual(here.map((s) => s.id), ['aaaa-bbbb']);
  const everywhere = allSessions(null);
  assert.deepEqual(everywhere.map((s) => s.id).sort(), ['aaaa-bbbb', 'cccc-dddd']);
  assert.equal(everywhere.find((s) => s.id === 'cccc-dddd').slug, 'C--y');
});

test('sessionMeta extracts title, cwd and entrypoint from the transcript head', () => {
  const f = path.join(profileDir('t1'), 'projects', 'C--x', 'meta-test.jsonl');
  fs.writeFileSync(f, [
    JSON.stringify({ type: 'summary', summary: 'fix the login bug' }),
    JSON.stringify({ type: 'user', cwd: 'C:\\work\\api', entrypoint: 'cli', message: { role: 'user', content: 'hello' } }),
  ].join('\n'));
  assert.deepEqual(sessionMeta(f), { title: 'fix the login bug', cwd: 'C:\\work\\api', entrypoint: 'cli' });
  assert.deepEqual(sessionMeta(path.join(profileDir('t1'), 'nope.jsonl')), { title: null, cwd: null, entrypoint: null });
});

test('isSyntheticPrompt flags harness-injected user messages, keeps real ones', () => {
  assert.ok(isSyntheticPrompt('<local-command-caveat>Caveat: The messages below were generated…'));
  assert.ok(isSyntheticPrompt('<command-name>/resume</command-name>'));
  assert.ok(isSyntheticPrompt('<local-command-stdout>This conversation is from a different directory</local-command-stdout>'));
  assert.ok(isSyntheticPrompt('<system-reminder>context</system-reminder>'));
  assert.ok(isSyntheticPrompt('   '));            // whitespace-only
  assert.ok(!isSyntheticPrompt('how can i have two accounts logged in for claude code?'));
  assert.ok(!isSyntheticPrompt('fix the login bug'));
});

test('sessionMeta skips local-command noise and titles from the first real prompt', () => {
  const f = path.join(profileDir('t1'), 'projects', 'C--x', 'noise.jsonl');
  fs.writeFileSync(f, [
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'cli', message: { role: 'user', content: '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: '<command-name>/resume</command-name>' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: '<local-command-stdout>This conversation is from a different directory</local-command-stdout>' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: 'do you have access to the governance repo?' } }),
  ].join('\n'));
  assert.equal(sessionMeta(f).title, 'do you have access to the governance repo?');
});

test('sessionMeta ignores tool_result user messages when picking a title', () => {
  const f = path.join(profileDir('t1'), 'projects', 'C--x', 'toolres.jsonl');
  fs.writeFileSync(f, [
    JSON.stringify({ type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'ok' }] } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: 'the actual question' } }),
  ].join('\n'));
  assert.equal(sessionMeta(f).title, 'the actual question');
});

test('sessionMeta falls back to null (untitled) when a session is pure resume-noise', () => {
  const f = path.join(profileDir('t1'), 'projects', 'C--x', 'allnoise.jsonl');
  fs.writeFileSync(f, [
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'cli', message: { role: 'user', content: '<local-command-caveat>Caveat…' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: '<command-name>/resume</command-name>' } }),
  ].join('\n'));
  assert.equal(sessionMeta(f).title, null);
});

test('promptTitle strips image tokens, rejects synthetic and empty text', () => {
  assert.equal(promptTitle('[Image: source: C:\\Users\\x\\.claude\\image-cache\\a.png]'), '[img]');
  assert.equal(promptTitle('[Image #2] fix the bug'), '[img] fix the bug');
  assert.equal(promptTitle('just a normal prompt'), 'just a normal prompt');
  assert.equal(promptTitle('<command-name>/resume</command-name>'), null);
  assert.equal(promptTitle('   '), null);
});

test('sessionMeta cleans image-attachment prompts into a tidy label', () => {
  const dir = path.join(profileDir('t1'), 'projects', 'C--x');
  const w = (id, content) => fs.writeFileSync(path.join(dir, id + '.jsonl'),
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'cli', message: { role: 'user', content } }));
  w('imgonly', [{ type: 'text', text: '[Image: source: C:\\Users\\Thinkpad\\.claude\\image-cache\\abc.png]' }, { type: 'image', source: {} }]);
  assert.equal(sessionMeta(path.join(dir, 'imgonly.jsonl')).title, '[img]');
  w('imgtext', [{ type: 'text', text: '[Image #1] why are the commissions different?' }, { type: 'image', source: {} }]);
  assert.equal(sessionMeta(path.join(dir, 'imgtext.jsonl')).title, '[img] why are the commissions different?');
});

test('listSessions hides empty resume-shells (no real prompt)', () => {
  const dir = path.join(profileDir('t1'), 'projects', 'C--shells');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'realone.jsonl'),
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'cli', message: { role: 'user', content: 'a real question' } }));
  fs.writeFileSync(path.join(dir, 'shell.jsonl'), [
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'cli', message: { role: 'user', content: '<local-command-caveat>Caveat…' } }),
    JSON.stringify({ type: 'user', message: { role: 'user', content: '<command-name>/resume</command-name>' } }),
  ].join('\n'));
  assert.deepEqual(listSessions('C--shells').map((s) => s.title), ['a real question']);
  assert.equal(listSessions('C--shells', { includeEmpty: true }).length, 2);
});

test('sessionMeta finds entrypoint even behind a huge first line', () => {
  // A big queue-operation blob as the first line must not hide the entrypoint
  // on the following user line (this is how SDK subagents were slipping through).
  const f = path.join(profileDir('t1'), 'projects', 'C--x', 'bigfirst.jsonl');
  const blob = 'x'.repeat(200_000);
  fs.writeFileSync(f, [
    JSON.stringify({ type: 'queue-operation', content: blob }),
    JSON.stringify({ type: 'user', cwd: 'C:\\p', entrypoint: 'sdk-cli', message: { role: 'user', content: 'agent prompt' } }),
  ].join('\n'));
  assert.equal(sessionMeta(f).entrypoint, 'sdk-cli');
});

test('isUserFacing keeps interactive sessions and drops SDK/subagent ones', () => {
  assert.ok(isUserFacing('cli'));
  assert.ok(isUserFacing('vscode'));
  assert.ok(isUserFacing(null));       // unknown → keep (conservative)
  assert.ok(!isUserFacing('sdk-cli'));
  assert.ok(!isUserFacing('sdk-ts'));
});

test('listSessions hides SDK subagents so the count matches /resume', () => {
  const dir = path.join(profileDir('t1'), 'projects', 'C--proj');
  fs.mkdirSync(dir, { recursive: true });
  const write = (id, entrypoint, text) => fs.writeFileSync(path.join(dir, id + '.jsonl'),
    JSON.stringify({ type: 'user', cwd: 'C:\\proj', entrypoint, message: { role: 'user', content: text } }));
  write('real0001', 'cli', 'the real conversation');
  for (let i = 0; i < 20; i++) write(`sub${String(i).padStart(5, '0')}`, 'sdk-cli', 'You are a subagent');
  const shown = listSessions('C--proj');
  assert.equal(shown.length, 1);
  assert.equal(shown[0].title, 'the real conversation');
  assert.equal(listSessions('C--proj', { includeSdk: true }).length, 21);
});
